CREATE TABLE comments (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content VARCHAR(1000) NOT NULL,
    created TIMESTAMPTZ DEFAULT now() NOT NULL,
    userid INT
        REFERENCES users(id),
    postid INT
        REFERENCES posts(id)
);